language: go
go:
 - 1.x
 - tip

cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod

go_import_path: kubepack.dev/onessl

install: true

script:
  - go build ./...
  - ./hack/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
